language: node_js
node_js:
  - "node"
before_install:
  - CC=gcc-5 && CXX=g++-5
install:
  - npm i -g yarn
  - yarn install
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
