language: node_js
node_js:
  - "node"
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install gcc-5.1 g++-5.1
  - sudo rm /bin/usr/g++
  - sudo ln -s /usr/bin/g++-5 /usr/bin/g++
install:
  - npm i -g yarn
  - yarn install
